-- SCRIPT TO CREATE tablespaces for schema and the schema owner&users
-- *** Directory Layout - Examples ***
-- ${ORACLE_BASE}/oradata/${ORACLE_SID}/MURACH
-- UNIX = /u01/oradata/ZDBT01L/MURACH/MURACH01_tblsp.dbf
-- Windows = E:\app\oracle\oradata\ZDBT01W\MURACH01
prompt>Creating tablespace
CREATE TABLESPACE MURACH
DATAFILE 'E:\app\oracle\oradata\ZDBT01W\MURACH\MURACH01_tblsp.dbf' SIZE 5M REUSE 
AUTOEXTEND ON NEXT 300 K MAXSIZE UNLIMITED
ONLINE;

commit;

prompt>Creating users
CREATE USER ap IDENTIFIED BY ap 
DEFAULT TABLESPACE MURACH TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON MURACH 
ACCOUNT UNLOCK;
CREATE USER ex IDENTIFIED BY ex 
DEFAULT TABLESPACE MURACH TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON MURACH 
ACCOUNT UNLOCK;
CREATE USER om IDENTIFIED BY om 
DEFAULT TABLESPACE MURACH TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON MURACH 
ACCOUNT UNLOCK;

prompt>Granting privileges
GRANT ALL PRIVILEGES TO ap;
GRANT RESOURCE TO ap;
GRANT ALL PRIVILEGES TO ex;
GRANT RESOURCE TO ex; 
GRANT ALL PRIVILEGES TO om;
GRANT RESOURCE TO om; 

commit;

quit;